version: '3.9'
services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/go/src/plesio-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
volumes:
  dbdata: