version: '3.9'
services:
  api:
    container_name: plesio-api
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/go/src/plesio-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: plesio-db
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  adminer:
    container_name: plesio-adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8081:8080"
  k6:
    image: loadimpact/k6:latest
    container_name: plesio-k6
    environment:
      - K6_STATSD_ENABLE_TAGS=true
      - K6_STATSD_ADDR=dd-agent:8125
    volumes:
      - ./k6:/k6
    depends_on:
      - dd-agent
      - api

  dd-agent:
    image: datadog/agent:latest
    container_name: plesio-dd-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
    env_file:
      - .env
    ports:
      - "8125:8125/udp"
volumes:
  dbdata: