// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/yamato0211/plesio-server/pkg/adapter"
	handler2 "github.com/yamato0211/plesio-server/pkg/adapter/http/handler"
	"github.com/yamato0211/plesio-server/pkg/adapter/ws/handler"
	"github.com/yamato0211/plesio-server/pkg/infra/mysql"
	"github.com/yamato0211/plesio-server/pkg/infra/redis"
	"github.com/yamato0211/plesio-server/pkg/usecase"
	"github.com/yamato0211/plesio-server/pkg/utils/config"
	"github.com/yamato0211/plesio-server/pkg/web/ws"
)

// Injectors from wire.go:

func InitializeMasterHandler() *adapter.MasterHandler {
	redisConfig := config.NewRedisConfig()
	redisRepository := redis.NewRedisRepository(redisConfig)
	hub := ws.NewHub(redisRepository)
	webSocketHandler := handler.NewWebSocketHandler(hub)
	dbConfig := config.NewDBConfig()
	db := mysql.NewMySQLConnector(dbConfig)
	userRepository := mysql.NewUserRepository(db)
	iUserUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler2.NewUserHandler(iUserUsecase)
	iRedisUsecase := usecase.NewRedisUsecase(redisRepository)
	redisHandler := handler2.NewRedisHandler(iRedisUsecase)
	masterHandler := adapter.NewMasterHandler(webSocketHandler, userHandler, redisHandler)
	return masterHandler
}
