// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"github.com/yamato0211/plesio-server/pkg/infra/mysql"
	"github.com/yamato0211/plesio-server/pkg/usecase"
	"github.com/yamato0211/plesio-server/pkg/utils/config"
)

// Injectors from wire.go:

func InitializeUserUsecase() usecase.IUserUsecase {
	dbConfig := config.NewDBConfig()
	db := mysql.NewMySQLConnector(dbConfig)
	userRepository := mysql.NewUserRepository(db)
	iUserUsecase := usecase.NewUserUsecase(userRepository)
	return iUserUsecase
}
