name: Build and Push Image

on:
  push:
    branches: 
     - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: "${{ secrets.GCLOUD_AUTH }}"

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/plesio-infra-407706/plesio-infra-407706-repository/plesio-server:${{ github.sha }} -f docker/prod/Dockerfile ./

    - name: Push
      run: |
        docker push asia-northeast1-docker.pkg.dev/plesio-infra-407706/plesio-infra-407706-repository/plesio-server:${{ github.sha }}

    - name: Checkout plesio-infra repository
      uses: actions/checkout@v2
      with:
        repository: 'yamato0211/plesio-infra'
        ref: 'main'
        token: ${{ secrets.PAT }}
        path: 'plesio-infra'

    - name: Update image tag in deployment.yaml
      run: |
        yq e -i '.spec.template.spec.containers[0].image = "asia-northeast1-docker.pkg.dev/plesio-infra-407706/plesio-infra-407706-repository/plesio-server:${{ github.sha }}"' plesio-infra/manifests/default/deployment.yaml

    - name: Commit and push changes
      run: |
        cd plesio-infra
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifests/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
